name: Update TypeScript shared cache

on:
  push:
    branches:
      - main

jobs:
  update-cache:
    name: Update TypeScript shared cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        shell: bash
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          echo -e "\n[install.scopes]\n\"@navikt\" = { token = \"$BUN_AUTH_TOKEN\", url = \"https://npm.pkg.github.com/\" }" >> bunfig.toml
          bun install --frozen-lockfile
          
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: .tsbuildinfo
          key: shared-${{ hashFiles('tsconfig.json') }} # This will never hit, but it is required.
          restore-keys: shared-${{ hashFiles('tsconfig.json') }}

      - name: Typecheck
        shell: bash
        run: bun run typecheck

      - name: Save shared cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .tsbuildinfo
          key: shared-${{ hashFiles('tsconfig.json') }}-${{ github.run_id }}
